# Generated by Django 4.1.13 on 2023-11-06 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_menu_book_createdat_book_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='book',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='filename',
            field=models.CharField(default=datetime.datetime(2023, 11, 6, 13, 49, 52, 876653, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
